# Generated by Django 4.0.6 on 2022-12-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='followed_by',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followee',
            new_name='user',
        ),
    ]
