# Generated by Django 4.0.6 on 2022-12-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Describe_company',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='hiring_for',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
