# Generated by Django 4.0.6 on 2022-12-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_describe_company_alter_user_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='dp',
            field=models.ImageField(blank=True, upload_to='frontend/src/static'),
        ),
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.IntegerField(default=0),
        ),
    ]
