# Generated by Django 4.0.6 on 2022-12-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_dp_profile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
