# Generated by Django 4.0.6 on 2023-01-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_application_accept_application_decline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verfied',
            field=models.BooleanField(default=False),
        ),
    ]
