# Generated by Django 4.0.6 on 2023-01-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_user_is_followed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_followed',
            new_name='is_follow',
        ),
        migrations.AddField(
            model_name='user',
            name='is_follower',
            field=models.BooleanField(default=False),
        ),
    ]
