# Generated by Django 4.0.6 on 2022-12-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_remove_like_like_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like_type',
            field=models.IntegerField(default=True),
        ),
    ]
