# Generated by Django 4.0.6 on 2022-12-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_alter_like_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
