# Generated by Django 4.0.6 on 2022-12-08 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0018_remove_like_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='like',
            name='likeusers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
