# Generated by Django 4.0.6 on 2022-12-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=True, upload_to='Decdict/frontend/src/static'),
        ),
    ]
