# Generated by Django 4.0.6 on 2022-12-14 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0026_post_likes_alter_comment_post_alter_like_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.question')),
                ('likeusers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='li', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
