# Generated by Django 4.0.6 on 2022-12-17 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0033_alter_answers_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='answerlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_like', to='post.answers')),
                ('likesuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
