# Generated by Django 4.0.6 on 2022-12-23 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0036_delete_answerlikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerlike', to='post.answers')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
