# Generated by Django 4.0.6 on 2022-12-31 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0038_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('Comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms', to='post.comment')),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
