# Generated by Django 4.0.6 on 2023-01-11 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0041_alter_save_question_saved_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save_question',
            name='saved_question',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='savess', to='post.question'),
        ),
    ]
