# Generated by Django 4.0.6 on 2022-12-08 06:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_post_likes_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default=True, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
