# Generated by Django 4.0.6 on 2022-12-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
