# Generated by Django 4.0.6 on 2022-12-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_remove_post_likes_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like_type',
        ),
    ]
