# Generated by Django 4.0.6 on 2022-12-08 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_like_like_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
