# Generated by Django 4.0.6 on 2022-12-08 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0019_remove_like_liked_by_like_likeusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likeusers',
        ),
        migrations.AddField(
            model_name='like',
            name='likeusers',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
