# Generated by Django 4.0.6 on 2022-12-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0031_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='Question',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='question1', to='post.question'),
        ),
    ]
