# Generated by Django 4.0.6 on 2022-12-23 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0035_answerlikes_delete_answerlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='answerlikes',
        ),
    ]
