# Generated by Django 4.0.6 on 2022-12-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0037_answer_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default=True, upload_to='frontend/src/static'),
        ),
    ]
