# Generated by Django 4.0.6 on 2023-01-11 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0040_save_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save_question',
            name='saved_question',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_question', to='post.question'),
        ),
        migrations.AlterField(
            model_name='save_question',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
