# Generated by Django 4.0.6 on 2023-03-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0042_alter_save_question_saved_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default=True, upload_to='static/'),
        ),
    ]
