# Generated by Django 4.0.6 on 2023-01-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='room',
        ),
    ]
