# Generated by Django 4.0.6 on 2023-01-07 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatmessage_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(default='27', on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom'),
        ),
    ]
