# Generated by Django 4.0.6 on 2022-12-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dp',
            new_name='profile_picture',
        ),
    ]
