# Generated by Django 4.0.6 on 2022-12-24 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user_follower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
                ('Phone_number', models.IntegerField()),
                ('resume', models.FileField(upload_to='frontend/src/static')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
