# Generated by Django 4.0.6 on 2022-12-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Accept',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='Decline',
            field=models.CharField(default=False, max_length=25),
        ),
        migrations.AddField(
            model_name='application',
            name='processing',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='frontend/src/static', verbose_name='resume'),
        ),
    ]
